server:
  port: 8080


spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:h2:tcp://localhost/~/sbsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true