server:
  port: 8080

spring:
  profiles:
    include:
      - discord

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/sbs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
