
discord:
  token: OTQxMDA5NzExNjMxODM5MjQy.YgPtlg.ZZLFYxCeaPg6_92NmC42zkTnLiU
  webhookURL: https://discord.com/api/webhooks/941006678319566848/-fQze9FiRrYR5Rje98nsMNH3XmFIneErtITRO4YzySWZJ4i6GmNGtzwW7O0j3JgORvj2